apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    # PLACEHOLDER: Replace with your IAM role ARN via Kustomize patch
    eks.amazonaws.com/role-arn: __ESO_ROLE_ARN__
