apiVersion: v1
kind: Namespace
metadata:
  name: reloader
  labels:
    app.kubernetes.io/name: reloader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reloader
  namespace: reloader
  labels:
    app.kubernetes.io/name: reloader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reloader
  labels:
    app.kubernetes.io/name: reloader
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reloader
  labels:
    app.kubernetes.io/name: reloader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reloader
subjects:
  - kind: ServiceAccount
    name: reloader
    namespace: reloader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader
  namespace: reloader
  labels:
    app.kubernetes.io/name: reloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reloader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reloader
    spec:
      serviceAccountName: reloader
      containers:
        - name: reloader
          image: ghcr.io/stakater/reloader:latest
          imagePullPolicy: IfNotPresent
          args:
            - --log-level=info
          env:
            - name: RELOADER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
