apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app-sa
  namespace: demo-app
  annotations:
    # PLACEHOLDER: Replace with your IAM role ARN via Kustomize patch
    eks.amazonaws.com/role-arn: __DEMO_APP_ROLE_ARN__
